### ISSUE TITLE
Exception thrown with script blockers

### ISSUE THREAD

**Issue by zombor** [continuon/vue-intercom#1]
If the user has a script blocker turned on in their browser (like [Disconnect](https://disconnect.me/)), we get an error like `window.Intercom is not a function`.

![type-error](https://cloud.githubusercontent.com/assets/170538/23382948/d56ab0c0-fd09-11e6-9b5d-1df42e6f8e43.png)

Any ideas how to mitigate this? Maybe check if `window.Intercom` exists in boot/init and return a null object if it doesn't? I'm ok with intercom features not working if this happens but eliminating the error would be nice too.

**Comment by johnnynotsolucky** [comment]
Thank you for reporting this! 

Yes, I think we can test whether Intercom is available on init, and only call `window.Intercom()` if its available.
