### ISSUE TITLE
$intercom.ready never triggers

### ISSUE THREAD

**Issue by maziarz** [continuon/vue-intercom#2]
I have installed this wrapper in a nuxt.js project and i am able to see that `window.Intercom` has been injected, but `$intercom.ready` is never triggered.

So i have a nuxt.js plugin with following:

```
import Vue from 'vue'
import VueIntercom from 'vue-intercom'

Vue.use(VueIntercom, { appId: 'removed' })
``` 

And in an arbitrary page i have:

```
  watch: {
    '$intercom.ready': function ready () {
      this.$intercom.boot()
      this.$intercom.show()
    }
  }
```

**Comment by cyberdude** [comment]
I have the same issue here!

**Comment by maziarz** [comment]
@cyberdude exact same setup or just same behaviour? I was able to get it up and running once. It seems to be some kind of async problem?

**Comment by cyberdude** [comment]
same problem different setup. I managed to temporarily fix it with a setTimeout on mount.

**Comment by maziarz** [comment]
Can you provide an example i am not quite sure why that has solved your problem. Since my case is related to watch its quite reactive.

**Comment by johnnynotsolucky** [comment]
@maziarz Thanks for reporting this!

I have it working with nuxt.js with the following set up:

nuxt.config.js:

```
  plugins: [{
    src: '~/plugins/vue-intercom.js',
    ssr: false
  }],
  build: {
    vendor: ['vue-intercom'],
    ...
  }
```

plugins/vue-intercom.js

```
import Vue from 'vue'
import VueIntercom from 'vue-intercom/src'

Vue.use(VueIntercom, { appId: 'app-id' })
```

pages/index.js

```
{
  ...
  watch: {
    '$intercom.ready': function ready () {
      this.$intercom.boot()
      this.$intercom.show()
    }
  }
}
```

I can reproduce the problem if I move the watcher to another page, and try to boot from there. For example, if you have the pages index.js and one.js and you load your app at `localhost:3000` then navigate to `/one` using nuxt-link; Intercom won't boot.

This happens because the ready state has already been set so the watcher never triggers.

A work around would be to boot Intercom from your main layout and update/show from your pages. The problem with this is if you want to show() immediately, there'll be a good chance that the Intercom script hasn't loaded completely and show won't be available.

Let me see if I can come up with a solution for this use case.

@cyberdude is what I described above similar to your problem too? Alternatively, could you log a new issue and provide some steps for me to reproduce please?

**Comment by maziarz** [comment]
So this is what i tried to do, which seems to work, but i am not sure ift is going to break. I took basis in the default layout which is used on all my pages at the moment.

`layouts/default.vue`

```
  mounted: function () {
    this.$intercom.boot()
  },
  watch: {
    '$intercom.ready': function ready () {
      console.log('intercom ready')
      this.$intercom.show()
    }
  }
```

**Comment by cyberdude** [comment]
That looks fine to me.  I don't force show so I don't have that problem. My problem was for the chat bubble to render. (Not pop the chat open)  

What I did was:

````
mounted: function () {
  setTimeout(() => {
    this.$intercom.boot()
  }, 500)
}
````

Don't do this though. Yours looks fine to me. I just needed a quick hack. The intercom variable is available so you can always interface with that. I think there's a window.intercom.ready or something like that

**Comment by johnnynotsolucky** [comment]
I've updated vue-intercom to defer actions until the Intercom script has loaded. Previously you'd have to rely on checking if `this.$intercom.ready` was true. Now you can call `'boot'`, then `'show'` without watching or checking the ready state. 

There are no breaking changes, watchers on `$intercom.ready` will still work, however I recommend calling boot when you set up your app; any other actions will be called afterwards

**Comment by maziarz** [comment]
Excellent job!

**Comment by chokies** [comment]
> @maziarz Thanks for reporting this!
> 
> I have it working with nuxt.js with the following set up:
> 
> nuxt.config.js:
> 
> ```
>   plugins: [{
>     src: '~/plugins/vue-intercom.js',
>     ssr: false
>   }],
>   build: {
>     vendor: ['vue-intercom'],
>     ...
>   }
> ```
> plugins/vue-intercom.js
> 
> ```
> import Vue from 'vue'
> import VueIntercom from 'vue-intercom/src'
> 
> Vue.use(VueIntercom, { appId: 'app-id' })
> ```
> pages/index.js
> 
> ```
> {
>   ...
>   watch: {
>     '$intercom.ready': function ready () {
>       this.$intercom.boot()
>       this.$intercom.show()
>     }
>   }
> }
> ```
> I can reproduce the problem if I move the watcher to another page, and try to boot from there. For example, if you have the pages index.js and one.js and you load your app at `localhost:3000` then navigate to `/one` using nuxt-link; Intercom won't boot.
> 
> This happens because the ready state has already been set so the watcher never triggers on the new page.
> 
> A work around would be to boot Intercom from your main layout and update/show from your pages. The problem with this is if you want to show() immediately, there'll be a good chance that the Intercom script hasn't loaded completely and show won't be available.
> 
> Let me see if I can come up with a solution for this use case.
> 
> @cyberdude is what I described above similar to your problem too? Alternatively, could you log a new issue and provide some steps for me to reproduce please?

im trying to follow this installation but im getting  Cannot read property 'boot' of undefined

btw im loading it on my component and using nuxt.js
